enum AddressingMode { Immediate };

struct Instruction {
    void (*instruction)();
    AddressingMode addressing_mode;
};

const struct Instruction instruction_table[16][16] = {{
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                          {NULL, Immediate},
                                                      },
                                                      {{NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate},
                                                       {NULL, Immediate}}};

class Cpu6502 {
   public:
    // Power on the CPU. This initializes register and memory contents.
    void Power();

    // The 6502 features three general-purpose registers, a status register, a
    // stack pointer, and a program counter.
    uint8_t accumulator;
    uint8_t register_x;
    uint8_t register_y;
    uint8_t status;
    uint8_t stack_pointer;
    uint16_t program_counter;

    // The 6502 features a 16-bit address space. Thus, there are 2 ** 16 =
    // 65,536 unique addresses that each store 1 byte.
    uint8_t memory[65536];

    // Internal variables.
    uint8_t opcode;
    AddressingMode addressing_mode;
};
